## Email Spam Filtering Using the Decsion Tree Classifier Approach

#### Part 1: Data Preprocessing

In [2]:
# import the libraries
import numpy as np                  # used for multidimensional array
import pandas as pd                 # used for import the dataset
import matplotlib.pyplot as plt     # used for ploting the graph

In [153]:
# import the dataset
dataset= pd.read_csv('/content/Breast Cancer Up Sampling.csv')
X= dataset.iloc[:, :-1].values     # predictor attributes
y= dataset.iloc[:, -1].values      # Target attribute

In [154]:
dataset.shape

(128, 9)

In [155]:
dataset.head()

BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [156]:
# split the dataset into test set and train set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [157]:
print(y_test)

[1 1 2 1 1 2 1 2 2 1 2 1 2 2 1 1 1 2 1 1 1 2 1 2 1 1]


#### Part 2: Building the  model

In [158]:
# import the Decision tree classider from scikit learn
from sklearn.tree import DecisionTreeClassifier

In [159]:
#initialize the Decision tree model
classifier=DecisionTreeClassifier(criterion ='entropy', random_state= 0)

In [160]:
# fir the model
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

#### Part 3:Predicted the result and Visulising the result

In [161]:
# predicted the result
y_pred = classifier.predict(X_test)
y_pred

array([1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1,
       1, 1, 1, 1])

In [162]:
# making a confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[7, 9],
       [4, 6]])

In [163]:
# accuracy score
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
ac

0.5

In [164]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.64      0.44      0.52        16
           2       0.40      0.60      0.48        10

    accuracy                           0.50        26
   macro avg       0.52      0.52      0.50        26
weighted avg       0.55      0.50      0.50        26

