## Blood Transfusion Service Center Data Set(UCI) prediction using SVM Classifier approach

#### Part 1: Data Preprocessing

In [1]:
# import the Libraries
import numpy as np                         # used for multidimensional array
import pandas as pd                        # used for import the dataset
import matplotlib.pyplot as plt            # used for plt the graph

In [105]:
# import the dataset
#dataset = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/blood-transfusion/transfusion.data')
dataset = pd.read_csv('/content/Breast Cancer Down Sampling.csv')
X = dataset.iloc[:,:-1].values          # predictor attributes
y = dataset.iloc[:, -1].values          # target attributes

In [106]:
dataset.shape

(103, 9)

In [107]:
dataset.head()

BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [108]:
# split the dataset into test set and train set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.2, random_state=0)

In [109]:
# feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

#### Part 2 : Building the SVM Model

In [110]:
# import support vector machine from scikit learn
from sklearn.svm import SVC

In [111]:
# init the svm model
classifier = SVC(kernel = 'linear', random_state=0)

In [112]:
# fit the training data into our SVM Classifer model
classifier.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [113]:
print(y_test)

[1 2 1 1 2 2 1 2 2 1 2 2 2 1 1 1 1 1 1 1 1]


#### Part 3: making a Prediction and Visualize the result

In [114]:
# making a prediction
y_pred = classifier.predict(X_test)
y_pred

array([1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1])

In [115]:
# confusion metric
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[6, 7],
       [1, 7]])

In [116]:
# accuracy score
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
ac

0.6190476190476191

In [117]:
from sklearn.metrics import precision_score
pc=precision_score(y_test, y_pred)
pc

0.8571428571428571

In [118]:
from sklearn.metrics import recall_score
rc=recall_score(y_test, y_pred)
rc

0.46153846153846156

In [119]:
from sklearn.metrics import f1_score
fc=f1_score(y_test, y_pred)
fc

0.6

In [120]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.86      0.46      0.60        13
           2       0.50      0.88      0.64         8

    accuracy                           0.62        21
   macro avg       0.68      0.67      0.62        21
weighted avg       0.72      0.62      0.61        21

