## Breast Cancer Coimbra Dataset(UCI) using Logistic Regression with Scikit Learn

#### Part 1: Data Preprocessing

In [1]:
# import the Libraries
import numpy as np                 # used for multidimensional array
import pandas as pd               # used for import the dataset

In [100]:
# import the dataset
dataset= pd.read_csv('/content/Breast Cancer Down Sampling.csv')
X= dataset.iloc[:,:-1].values      # predictor attribute
y= dataset.iloc[:,-1].values       # Target attribute

In [101]:
dataset.shape

(103, 9)

In [102]:
dataset.head()

BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [103]:
# Split the dataset into test set and Train set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [104]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

#### Part 2: Building the Logistic Regression Model

In [105]:
# import the Logistic regression model from scikit learn
from sklearn.linear_model import LogisticRegression

In [106]:
# init the model
LG = LogisticRegression(random_state=0)

In [107]:
# fit the training data into our model
LG.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [108]:
print(y_test)

[1 2 1 1 2 2 1 2 2 1 2 2 2 1 1 1 1 1 1 1 1]


#### Part 3: Making a prediction and Visualize the result

In [109]:
# predicted the result
y_pred = LG.predict(X_test)
y_pred

array([1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1])

In [110]:
# Confusion metrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[7, 6],
       [1, 7]])

In [111]:
# Accuracy score
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test, y_pred)
ac

0.6666666666666666

In [112]:
from sklearn.metrics import precision_score
pc=precision_score(y_test, y_pred)
pc

0.875

In [113]:
from sklearn.metrics import f1_score
fc=f1_score(y_test, y_pred)
fc

0.6666666666666667

In [114]:
from sklearn.metrics import recall_score
rc=recall_score(y_test, y_pred)
rc

0.5384615384615384

In [115]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.88      0.54      0.67        13
           2       0.54      0.88      0.67         8

    accuracy                           0.67        21
   macro avg       0.71      0.71      0.67        21
weighted avg       0.75      0.67      0.67        21

